### ISSUE TITLE
The "Submit" button doesn't do anything

### ISSUE THREAD

**Issue by trialism** [flathub/com.microsoft.Teams#9] opened 2020-02-03 08:33 UTC
But the teams app consumes 8% CPU and does nothing. I'm using manjaro.

**Comment by Lctrs** [comment] 2020-02-03 09:09
Which submit button ? Where is it located in the app ? Could you provide steps to reproduce the issue ?

**Comment by trialism** [comment] 2020-02-03 14:36
The "Submit" button at the login prompt.

**Comment by Lctrs** [comment] 2020-02-03 14:50
Can't reproduce... Will try something.

**Comment by Lctrs** [comment] 2020-02-12 09:38
Hi. Could you please test #10 and tell me if it has any effect ?

**Comment by cajosc** [comment] 2020-02-17 09:04
I have the same issue with federated login. The version from #10 doesn't solve it.

**Comment by cajosc** [comment] 2020-02-17 09:18
I get the following errors when running the build from #10 with `-vvv`:

```
libsecret-Message: 10:05:13.468: secret portal is not available: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.Secret”
libsecret-Message: 10:05:13.482: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
(node:2) UnhandledPromiseRejectionWarning: Error: org.freedesktop.DBus.Error.ServiceUnknown
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Lctrs** [comment] 2020-02-17 09:22
@cajosc Thanks for the log.

Is `flatpak run --talk-name=org.freedesktop.secrets com.microsoft.Teams` resolving your issue ?

**Comment by cajosc** [comment] 2020-02-17 09:26
@Lctrs Yes, that did the trick!

**Comment by Lctrs** [comment] 2020-02-17 09:29
@trialism Would be great if you can confirm that the above command fixes your issue as well.

**Comment by Lctrs** [comment] 2020-02-17 09:35
@cajosc The fix should lands in an hour.

**Comment by trialism** [comment] 2020-02-17 12:47
@Lctrs it didn't work for me.

**Comment by Lctrs** [comment] 2020-02-17 13:05
@trialism Could you run the following command in a terminal and paste here the output of the third one please ?

1. `flatpak kill com.microsoft.Teams`
2. `flatpak update`
3. `flatpak run com.microsoft.Teams -vvv`

**Comment by trialism** [comment] 2020-02-17 14:23
```
Gtk-Message: 15:22:14.406: Failed to load module "canberra-gtk-module"
(node:3) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners add
ed. Use emitter.setMaxListeners() to increase limit
libsecret-Message: 15:22:35.420: secret portal is not available: GDBus.Error:org.freedesktop.DBus.Error.InvalidAr
gs: No such interface: „org.freedesktop.portal.Secret”
libsecret-Message: 15:22:35.458: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The
 name org.freedesktop.secrets was not provided by any .service files
(node:3) UnhandledPromiseRejectionWarning: Error: The name org.freedesktop.secrets was not provided by any .servi
ce files
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 (rejection id: 1)
(node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reject
ions that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Lctrs** [comment] 2020-02-17 14:29
Looks like there is no service providing `org.freedesktop.secrets` on your system. If you install one, it should work.

I'm only aware of Gnome Keyring for providing this.

**Comment by trialism** [comment] 2020-02-18 09:05
The dependency on keyring software should be removed since it's not a dependency of flatpak.

**Comment by Lctrs** [comment] 2020-02-18 09:11
There is no dependency on Gnome Keyring. There is a dependency on the service `org.freedesktop.secrets`. That's how this app works. Nothing we can do on our side.

**Comment by Lctrs** [comment] 2020-02-18 09:14
Since you've been provided a working fix, I'm closing this issue.

**Closed by Lctrs** 2020-02-18 09:14 UTC

**Comment by bilelmoussaoui** [comment] 2020-02-18 09:16
The secret service can't be sandboxed yet. We depend on the host to provide that for now, hence the requirement to have gnome-keyring installed as it's the only available implementation.
