### ISSUE TITLE
Video output does not work

### ISSUE THREAD

**Issue by fdcds** [flathub/com.microsoft.Teams#70] opened 2021-08-03 08:15 UTC
The Microsoft Teams app does not show any video here. The webcam preview (outside of calls and in a call) is black and other participants in a call are displayed as if they had their webcam turned off. Their screen shares are also not displayed: Teams changes the arrangement of tiles or even puts a till onto the full screen, but the tiles still show only the initials of the person -- as if they had their webcam turned off. Deactivating GPU video decoding in the app's settings does not help.

```
Microsoft Teams - Microsoft Teams for Linux is your chat-centered workspace in
Office 365

          ID: com.microsoft.Teams
         Ref: app/com.microsoft.Teams/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.4.00.13653
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 4.7 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: ad664a8a32fcbf6f0e039369375d44411b00b1813ff1e9c0bcedead5e9b56dee
      Parent: 254d23b8f87936f75cfe86c965febec7f1d05c134475d60572343db2baa2d1a6
     Subject: Update teams.deb to 1.4.00.13653 (6733cf6e)
        Date: 2021-06-08 09:46:20 +0000
```

```
❯ flatpak --version
Flatpak 1.10.2
```

```
❯ uname -r
5.13.6-100.fc33.x86_64
```

Using Fedora 33 with the KDE desktop on X11.

**Comment by jwillikers** [comment] 2021-08-03 15:10
Same problem on Fedora 34 using default GNOME running under Wayland.

**Comment by tunix** [comment] 2021-08-04 06:55
Same problem on Pop!_OS 21.04 (X11).

**Comment by fdcds** [comment] 2021-08-04 07:31
I also noticed the same problem with the Teams web UI in Chromium 91.0.4472.164 on Fedora 33. The RPM of Teams version 1.4.00.13653 works fine.

**Comment by rombert** [comment] 2021-08-04 08:16
Same problem on OpenSUSE Tumbleweed. Worked yesterday, does not work today

```flatpak info com.microsoft.Teams 

Microsoft Teams - Microsoft Teams for Linux is your chat-centered workspace in
Office 365

          ID: com.microsoft.Teams
         Ref: app/com.microsoft.Teams/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.4.00.13653
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 4.7 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: ad664a8a32fcbf6f0e039369375d44411b00b1813ff1e9c0bcedead5e9b56dee
      Parent: 254d23b8f87936f75cfe86c965febec7f1d05c134475d60572343db2baa2d1a6
     Subject: Update teams.deb to 1.4.00.13653 (6733cf6e)
        Date: 2021-06-08 09:46:20 +0000
~ > flatpak --version
Flatpak 1.11.2
~ > uname -r
5.13.4-1-default
~ > cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20210801"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210801"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210801"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo```

**Comment by tunix** [comment] 2021-08-04 08:38
Reinstalling Teams fixes the problem for a while. Than it occurs again after a reboot or restart of the app.

**Comment by mkatt** [comment] 2021-08-04 11:37
Seems that it's something related to the `rect-overlay` binary and the new Teams version.

After a downgrade, the things are working:

```
sudo flatpak update --commit=254d23b8f87936f75cfe86c965febec7f1d05c134475d60572343db2baa2d1a6 com.microsoft.Teams
```

and if you want to stop flatpak from updating this version of teams to the latest broken (until it's resolved, at least), you can do:

```
sudo flatpak mask flathub com.microsoft.Teams
```

**Comment by mkatt** [comment] 2021-08-04 11:39
Possible duplicate of https://github.com/flathub/com.microsoft.Teams/issues/69

**Comment by rombert** [comment] 2021-08-04 13:47
> Seems that it's something related to the `rect-overlay` binary and the new Teams version.
> 
> After a downgrade, the things are working:
> 
> ```
> sudo flatpak update --commit=254d23b8f87936f75cfe86c965febec7f1d05c134475d60572343db2baa2d1a6 com.microsoft.Teams
> ```
> 
> and if you want to stop flatpak from updating this version of teams to the latest broken (until it's resolved, at least), you can do:
> 
> ```
> sudo flatpak mask flathub com.microsoft.Teams
> ```

That seems to fix the problem for me, thanks a lot for posting this!

**Comment by jwillikers** [comment] 2021-08-04 14:14
I can confirm this is also working for me so far. Much appreciated!

**Comment by tunix** [comment] 2021-08-06 06:46
@mkatt - out of curiosity, which project does this commit id belong to? i couldn't find it inside this repo.

**Comment by mkatt** [comment] 2021-08-06 07:08
@tunix , it's a `flatpak` commit id[0], from flathub (not a git commit).

[0] https://docs.flatpak.org/en/latest/tips-and-tricks.html?highlight=downgrade#downgrading

**Comment by ravomavain** [comment] 2021-08-19 10:48
The startup script in the original .deb file pass some extra parameters to the teams binary : `--disable-namespace-sandbox --disable-setuid-sandbox`
The wrapper script that replace it in this flatpak doesn't have those parameters (but support extra parameters via "$@")
I tried running the last version with those parameters :
`com.microsoft.Teams --disable-namespace-sandbox --disable-setuid-sandbox`
And it seams to fix the video output problems.

**Closed** 2021-08-19 11:58 UTC
