### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by bluewww** [flathub/com.microsoft.Teams#54] opened 2021-03-02 11:23 UTC
On a centos 7.9 machine I get the following error trying to update microsoft teams
```bash
bluew:[~]: flatpak update
Looking for updates...
Updating in user:
com.microsoft.Teams/x86_64/stable flathub 0aec9650ee1d
Is this ok [y/n]: y
Updating for user: com.microsoft.Teams/x86_64/stable from flathub
[####################] Downloading files: 1/1 76.3 MB (10.9 MB/s)         ar: error while loading shared libraries: libbfd-2.35.2.so: cannot open shared object file: No such file or directory
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Error: Failed to update com.microsoft.Teams/x86_64/stable: While trying to apply extra data: apply_extra script failed, exit status 512
error: There were one or more errors
```

**Comment by Lctrs** [comment] 2021-03-02 12:20
Duplicate of #49

**Closed by Lctrs** 2021-03-02 12:20 UTC
